name: Build and Deploy 11ty Site
on:
  push:
    branches: [ master ]  # Using master instead of main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Update this from '16' to '18'
          
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build site
        run: |
              export NODE_ENV=production
              export ELEVENTY_ENV=production
              npx @11ty/eleventy
        
        
      - name: Create .nojekyll file
        run: touch _site/.nojekyll
        
      - name: Copy CNAME to _site directory
        run: cp CNAME _site/ || echo "No CNAME file found"
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: _site
